export enum HttpStatusCode {
    OK = 200,
    BAD_REQUEST = 400,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    UNPROCESSABLE_CONTENT = 422,
    SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
}

export enum ApiErrorCode {
    CONFLICT = 'CONFLICT',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    NOT_FOUND = 'NOT_FOUND',
    SERVER_ERROR = 'SERVER_ERROR',
}

export const API_TIMEOUT_MILLISECONDS = 10000;
